### ISSUE TITLE
fd 관련해서 질문입니다!

### ISSUE THREAD

**Issue by Ejaeda** [Ejaeda/42_Study_Group#12]
https://github.com/Ejaeda/42_Study_Group/blob/1c9c1b240b992141cdb5da8b41cb14f313ba7e94/jun/piscine/c10/ex00/srcs/main.c#L43

fd는 0 ,1, 2 고정값 이후에 3부터 파일오픈 시 부여될 수 있는데

프로세스 실행중에 파일을 open 하면 커널이 해당 프로세스의 fd 숫자 중에 사용하지 않는 가장 작은 값을 할당

예를들어 hello가 적혀있는  a.txt 파일에게 접근해서 fd = 3을 부여 받았고 이를 출력할 때

형 코드에서 char 한칸짜리 변수를 설정하고 while(read)와 write(1, &, 1)이 반복되어

hello를 출력하고 있는데 반복문 자체에는 h를 출력하고 e를 출력하기 위한 움직임이 없잖아요

직관적으로 먼가 동일한 행동이 반복되어 hhhhhhhhh 가 나올 것 같지만

아래처럼 이해하는게 맞나요?

read의 반환값으로 읽어온 바이트 수 1 + 그 읽은 수를 출력하는 write (1, &, 1)

애초에 파일을 읽어왔다는 행동에서 버퍼에 hello가 담기고 1개를 read하고 h 한글자 write 

그 다음 read 1 되는 위치는 자동으로 이동되어 e를 읽어온다?

**Comment by ji-junhyuk** [comment]
응! read함수는 연 파일 기준으로 하나씩 읽어나가니깐 두번째 read함수는 두번째글자 읽는거라고 생각하면 됨. 
"hello"를 읽을 때.
open()-> 
read()함수를 호출: 한 글자 출력(h).  read()함수호출: 그 다음 글자 출력(e).

근데 open()-> read함수 호출(h) 다시 close()하고 open() -> read함수 호출(h).

**Comment by Ejaeda** [comment]
감사합니다!
