### ISSUE TITLE
main 함수에 정의되어 있는데 여기서 함수 선언을 해준 이유가 있으신가요???

### ISSUE THREAD

**Issue by Ejaeda** [Ejaeda/42_Study_Group#8]
https://github.com/Ejaeda/42_Study_Group/blob/7820eacee0817e518d810a3ee826c6e5a7ae8783/jun/piscine/c08/ex03/ft_point.h#L22

**Comment by ji-junhyuk** [comment]
큰 이유는 없음~
header에 넣어두면 어디서든 쓰기 편하니깐!!
